#
# docker-compose.yml
#
# FOR CI ONLY.
#
#   Using Docker Compose helps us test the library on both Node 14 and Node 16. The purpose is _not_ to burden the
#   developer experience (and documentation) with Docker - this file is only used by the CI runs.
#
# Context:
#   - Cloud Build, with 'firebase-ci-builder' image in the Container Registry
#
# Environment values (Cloud Build):
#   - 'CI_BUILDER_IMAGE'
#   - 'NODE': "14"
#
#   - pwd: /workspace
#
# Intentions:
#   - Test with Node 14
#   - Test with Node 16
#
# Docker Compose (v3) note:
#   BE CAREFUL with use of pipe ('|') or '&&' in the commands! See -> https://stackoverflow.com/a/68590318/14455
#
# References:
#   Overview of Docker Compose (Docker docs)
#     -> https://docs.docker.com/compose/
#   Compose file version 3 reference
#     -> https://docs.docker.com/compose/compose-file/compose-file-v3/
#
version: '3.0'

services:
  # Launch Firebase Emulators, with certain warning and info messages suppressed.
  #
  emul:
    image: ${CI_BUILDER_IMAGE:-firebase-ci-builder:9.16.0-node16-npm7}
    ports:
      - "4000:4000"
      - "5002:5002"
      - "6767:6767"
      # Keep ports aligned with 'firebase.json'
    volumes:
      - .:/work
    working_dir: /work
    command: bash -o pipefail -c
      'echo "Launching Docker... 🐳" &&
      firebase emulators:start --project=demo-1
        | grep -v -E "Detected demo project ID|You are not signed in to the Firebase CLI|You are not currently authenticated"'
      # Keep project ID synced with 'package.json' and 'sample/test-fns/setup.jest.js'

  # Test with any supported Node version
  #
  # Note: CI has already done 'npm install'.
  #
  test:
    build: dc-tools/n${NODE-16}/
    volumes:
      - .:/work
    working_dir: /work
    command: sh -o pipefail -c
      'wait-for-it emul:6767 &&
      npm run test:all
      '
    environment: ['EMUL_HOST=emul']
      #
    depends_on: ['emul']
    profiles: ['manual']

## DEPRECATED (without using 'build:')
#  test:
#    image: node:${NODE-16}-alpine
#    volumes:
#      - .:/work
#    working_dir: /work
#    entrypoint: /bin/sh
#    command: -o pipefail -c
#      'npm config set update-notifier false &&
#      npx wait-for emul:6767 &&
#      npm run test:all
#      '
#    environment: ['EMUL_HOST=emul']
#      #
#    depends_on: ['emul']
#    profiles: ['manual']

  # Versions (Aug 2021):
  #
  # image   | Node version | npm version
  # ---     | ---          | ---
  # node:16 | v16.7.0      | 7.20.3
  # node:14 | v14.17.5     | 6.14.14
  #
  debug:
    image: node:${NODE}
    #volumes:
    #  - .:/work
    #working_dir: /work
    command: bash -o pipefail -c
      'node --version &&
      npm --version
      '
    profiles: ['manual']
