#
# ci/cloudbuild.yaml
#
# Intention:
#   Check that the project installs and runs the tests.
#
# Triggers:
#   - PR is made or changed; changes affect files other than '*.md', '.images/*', 'images/*'.
#
# Cloud Build project:
#   https://console.cloud.google.com/cloud-build/triggers?project=ci-builder
#
# Uses images:
#   - node:16-alpine
#   - firebase-ci-builder   (pushed to Container Registry)
#   - docker
#
# Runtime environment:
#   - Current directory is '/workspace'
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Note:
#   Using 'node:16' to run 'npm install' means that the packages are installed as root, and 'node_modules' is read-only
#   to regular users (of other images). This is normally not a concern.
#

steps:
  # DEBUG
#- name: node:16-alpine
#  entrypoint: sh
#  args: ['-c', 'env']

#--- Node 16 ---
#
- name: node:16-alpine
  entrypoint: npm
  args: ['install']

# Launch emul, keeps running in the background.
#
# Note: It's vital to wrap the command in Docker. This allows it to remain running for the rest of the steps.
#
- name: gcr.io/cloud-builders/docker
  args: [
    'run', '-d', '-p', '6767:6767', '-p', '5002:5002',
      '-v', '${_PWD}:/work', '-w', '/work',
      '--name', 'emul',
      '--network', 'cloudbuild',    # needed for showing the ports in the other steps
      'gcr.io/${PROJECT_ID}/firebase-ci-builder:${_BUILDER_TAG}',
    'npm', 'run', 'start'
  ]

# DEBUG: Is 'emul' visible??
- name: node:16-alpine
  entrypoint: sh
  args: ['-c', "host emul"]

- name: node:16-alpine
  entrypoint: npm
  args: ['run', '//ci:1']
  env:
    - EMUL_HOST=emul
# /DEBUG

- name: node:16-alpine
  entrypoint: npm
  args: ['run', 'ci:test']
  env:
    - EMUL_HOST=emul

# --- Timeout
#
# Cloud Build
#   (node 16):  1m53s, 1m58s (x2), 2m17s
#
# Earlier versions
#   (node 14):  1m48s, 1m53s
#
#timeout: 240s
timeout: 400s

substitutions:
  _BUILDER_TAG: 9.17.0-node16-npm7
  _PWD: /workspace
    # tbd. How to escape and use the 'PWD' env.var. in a command? #SO #help
