#
# cloudbuild.yaml
#
# Builder image:
#   https://github.com/akauppi/firebase-ci-builder
#
# Runtime environment:
#   - Current directory is '/workspace'
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Triggers:
#   - functional changes to 'master' branch
#     - changes only affecting '.md' files are excluded
#

steps:
  # DEBUG
#- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
#  entrypoint: bash
#  args: ['-c', 'env']

- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['install']
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['run','ci']

# --- Timeout
#
# Takes:
#   CI: 1m48s, 1m53s
#
timeout: 240s

substitutions:
  _BUILDER_TAG: 9.12.1-node16-npm7
