#
# cloudbuild.yaml
#
# Builder image:
#   https://github.com/akauppi/firebase-ci-builder
#
# Runtime environment:
#   - Current directory is '/workspace'
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Triggers:
#   - functional changes to 'master' branch
#     - changes only affecting '.md' files are excluded
#

steps:
  # DEBUG
#- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
#  entrypoint: bash
#  args: ['-c', 'env']

# Node 14
#
# Passes if timeouts are 5000ms (2655 ms for fns; 2414 for rules)
#
- name: node:14-alpine
  entrypoint: npm
  args: ['install']
- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['run', 'test']
  env: [
    'CI_BUILDER_IMAGE=gcr.io/${PROJECT_ID}/firebase-ci-builder:${_BUILDER_TAG}',
    'NODE=14'
  ]

# Node 16
# ...
# Have problems running with Node 16, under Docker Compose, so left for #later.
#
# Ideally, it would be nice to run CI jobs on both versions. `#contribute`?

# --- Timeout
#
# Takes:
#   CI: 1m48s, 1m53s
#
timeout: 240s

substitutions:
  _BUILDER_TAG: 9.16.0-node16-npm7
  _DOCKER_COMPOSE_TAG: 1.29.2
