#
# ci/cloudbuild.yaml
#
# Intention:
#   Check that the project installs and runs the tests.
#
# Triggers:
#   - PR is made or changed; changes affect files other than '*.md', '.images/*', 'images/*'. [1]
#
#     [1]: Also some subfolders are ignored by the CI trigger, say 'sh', ... (the list may change; they should be
#          included also in '../.gcloudignore').
#
# Cloud Build project (private access):
#   https://console.cloud.google.com/cloud-build/triggers?project=ci-builder
#
# Uses images:
#   - node:16-alpine
#   - firebase-ci-builder   (pushed to Container Registry)
#   - docker/compose
#
# Runtime environment:
#   - Current directory is '/workspace'
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Note:
#   Using 'node:16' to run 'npm install' means that the packages are installed as root, and 'node_modules' is read-only
#   to regular users (of other images). This is normally not a concern.
#

steps:
  # DEBUG
#- name: node:16-alpine
#  entrypoint: sh
#  args: ['-c', 'env']

# Install
#
- name: node:16-alpine
  entrypoint: sh
  args: ['-c', 'npm install && npm --prefix sample.dc install']

# Launch emul/warm-up in DC, keeps them running in the background.
#
# Note: Using the '... run warmed-up' approach (same as manual) lead for some reason to this:
#     <<
#        Step #1: ERROR: for warmed-up  Container "fa3f97950a65" is unhealthy.
#     <<
#
#     However, we don't need to use that step in CI, since warm-up would always happen just once.
#
- name: docker/compose:${_DOCKER_COMPOSE_TAG}
  args: ['-f', 'docker-compose.yml', '-f', 'docker-compose.ci.yml', 'up', '-d', 'warm-up']
  dir: sample.dc
  env:
    - CI_BUILDER_IMAGE=gcr.io/${PROJECT_ID}/firebase-ci-builder:${_BUILDER_TAG}

- name: node:16-alpine
  entrypoint: npm
  args: ['run', 'ci:test']
  dir: sample.dc
  env:
    - EMUL_HOST=emul

# --- Timeout
#
# Cloud Build
#   xxx s
#
# Earlier versions (just for comparison)
#   (node 16):  1m53s, 1m58s, 2m17s
#   (node 14):  1m48s, 1m53s
#
#timeout: 240s
timeout: 400s

substitutions:
  _BUILDER_TAG: 9.17.0-node16-npm7
  _DOCKER_COMPOSE_TAG: 1.29.2
    #
    # ^-- Note: That's tremendously (10 months; Mar 2022) out of date!  But that's not the cause of problems.
    #           Our tests should pass also with it.

