#
# cloudbuild.yaml
#
# Builder image:
#   https://github.com/akauppi/firebase-ci-builder
#
# Runtime environment:
#   - Current directory is '/workspace'
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Triggers:
#   - functional changes to 'master' branch
#     - changes only affecting '.md' files are excluded
#
# Notes:
#   - cannot use '<<: &anchor' and '<<: *anchor' YAML syntax in Cloud Build, it seems.

substitutions:
  _BUILDER_TAG: 9.12.1-node16-npm7

steps:
  # DEBUG
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: bash
  args: ['-c', 'env']

- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['install']
- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
  entrypoint: npm
  args: ['test']

# --- Timeout
#
# Takes:
#   CI: 1m48s
#
timeout: 240s
